name: Local GIT Actions
on: [ push, pull_request ]

jobs:
  local-action-test:
    name: 'Test Local'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Tests
        run: |
          echo "oi"
          echo $test_var1
          echo $test_var2          
          echo $secret
        env:
          test_var1: ${{vars.VAR_A}}
          test_var2: ${{vars.VAR_B}}
          secret: ${{secrets.SECRET}}

